INSERT INTO `Events` (event_id, event_name, event_type, event_date, event_link, event_location, event_description, event_image, event_price) VALUES ('1', 'Orrin Evans Trio', 'Music', 'Thursday August 29 2019 - Sunday September 1 2019', 'https://www.timeout.com/newyork/music/orrin-evans-trio', 'Jazz Standard , Flatiron', 'One of the leading pianists of his generation, Evans regularly blurs the lines between bluesiness and abstraction, muscularity and tenderness. He is been busy as of late replacing the masterful Ethan Iverson in jazz-pop crossover trio the Bad Plus, but here he is heading his own combo. Over this four-night engagement, expect him to play from his most recent release, The Evolution of Oneself.', 'https://media.timeout.com/images/100651069/1372/772/image.jpg', '30');

INSERT INTO `Events` (event_id, event_name, event_type, event_date, event_link, event_location, event_description, event_image, event_price) VALUES ('2', 'Abdu Ali + Dreamcrusher', 'Music', 'Friday September 6 2019', 'https://elsewherebrooklyn.com', 'Elsewhere , Bushwick', 'Baltimore-born outsider-artist Ali raps and sings over a "post-afro-futurist" mix of jazz sounds, B-more club beats and punk attitude—a fitting pairing to the glitchy synth anarchy, blown-out speaker textures and sinister screeches Luwayne Glass peddles as Dreamcrusher.', 'https://f4.bcbits.com/img/a1933006973_10.jpg', '10');

INSERT INTO `Events` (event_id, event_name, event_type, event_date, event_link, event_location, event_description, event_image, event_price) VALUES ('3', 'Tyler, the Creator', 'Music', 'Thursday September 12 2019', 'https://www.timeout.com/newyork/music/tyler-the-creator', 'Gardens', 'In recent years, anarchic Odd Future leader Tyler Okonma moved beyond the now played-out shock rhymes and into surprisingly earnest territory with his newly released Igor and 2017s Flower Boy.', 'https://media.timeout.com/images/100476233/1372/772/image.jpg', '49');

INSERT INTO `Events` (event_id, event_name, event_type, event_date, event_link, event_location, event_description, event_image, event_price) VALUES ('4', 'BABYMETAL', 'Music', 'Sunday September 15 2019', 'https://www.timeout.com/newyork/music/babymetal', 'Terminal 5 , Hells Kitchen', 'Over-the-top spectacle is part of metals DNA, but when it comes to pure batshit bombast, BABYMETAL might just have everyone from Alice Cooper to Iron Maiden beat. This Japanese import juxtaposes the fizzy J-pop song-and-dance of three pixieish teens with mercilessly steroidal shred, raging pyrotechnics and camp-macabre chills. BABYMETAL’s first NYC show in three years ought to fulfill your yearly WTF quota and then some.', 'https://media.timeout.com/images/101686631/1372/772/image.jpg', '59');

INSERT INTO `Events` (event_id, event_name, event_type, event_date, event_link, event_location, event_description, event_image, event_price) VALUES ('5', 'Afropunk Festival', 'Music', 'Saturday, August 25 & Sunday, August 26, 2019', 'https://www.timeout.com/newyork/music/afropunk-festival-guide', 'Terminal 5 , Hells Kitchen', 'Afropunk Festival is an annual event that takes place in August at Brooklyns Commodore Barry Park. Over the course of a weekend, Afropunk 2018—NYCs outdoor summer music festival celebrating multicultural arts—hosts a wide array of well-known musical artists (including some of the biggest hip-hop artists), as well as food trucks, live art, a craft market and more. Additionally, Afropunk strives to raise multicultural awareness in New York City with its Activism Row initiative.', 'https://media.timeout.com/images/103962077/1372/772/image.jpg', '110');

INSERT INTO `Events` (event_id, event_name, event_type, event_date, event_link, event_location, event_description, event_image, event_price) VALUES ('6', 'Queer/Art/Film', 'Art', 'Monday August 26 2019', 'https://www.timeout.com/newyork/lgbt/queer-art-film', 'IFC Center , West Village', 'IFCs always-excellent queer viewing series roars back with a killer 2019 season. The summer season promises a high camp showcase worthy of World Pride, with screenings of Split, Death Becomes Her, Thank God Its Friday and 9 to 5..', 'https://media.timeout.com/images/100470723/1372/772/image.jpg', '110');

INSERT INTO `Events` (event_id, event_name, event_type, event_date, event_link, event_location, event_description, event_image, event_price) VALUES ('7', 'Queer Memoir: Birthdays', 'Other', 'Sunday, December 1, 2019', 'https://www.eventbrite.com/e/queer-memoir-birthdays-tickets-59778163095?aff=ebdssbdestsearch', 'Caveat', 'Queer Memoir is NYCs award-winning longest running and most ridiculously earnest multi-venue themed LGBT storytelling show. Every month we join together some of NYCs best known storytellers and folks who have never been on a stage in their lives. Queer Memoir is an opportunity to give voice to our collective queer experiences, preserve and document our complex queer history and celebrate the ritual and community-building value of storytelling. And have fun of course. We have a lot of fun!', 'https://cdn.evbuc.com/images/67757461/207096185123/1/logo.20190806-190234', '11');

INSERT INTO `Events` (event_id, event_name, event_type, event_date, event_link, event_location, event_description, event_image, event_price) VALUES ('8', 'Queer Monologues and Short Plays Too', 'Performance Arts', 'September 15, 2019', 'https://www.eventbrite.com/e/queer-monologues-and-short-plays-too-tickets-67930962337?aff=ebdssbdestsearch', 'Alchemical Studios', 'Readings of the LGBTQ. Enjoy a night of fun, laughter and tears. Add a touch of our history for a most interesting evening. Written and Directed by, Yvonne Hernandez
Cast: Ginger Kipps, Andrea Sears, Austin Napoleon, Nathan Harding, Dujuana Sharese, Louise Heller, Thaddius Novack, Sarah Teed', 'https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F67515197%2F316461822923%2F1%2Foriginal.20190804-200013?w=800&auto=compress&rect=0%2C344%2C2448%2C1224&s=867affa2f6ac626c0552ce277996e57d', '15');

INSERT INTO `Events` (event_id, event_name, event_type, event_date, event_link, event_location, event_description, event_image, price, event_price) VALUES ('9', 'Yaeji', 'Music', 'October 2019', 'https://www.timeout.com/newyork/clubs/yaeji', 'This local producer melds house and hip-hop elements into a distinctive mix that is indisputably alluring—her singles Drink I am Sippin On and Raingurl have upwards of two-million plays at this point. However, the singer is not one to hoard the spotlight. Previous shows have featured her collaborating with a Korean restaurant to make curry for the crowds, in attempt to recreate the familial, communal atmosphere of gathering for a home-cooked meal. This should also feel like a family affair, as the show is bill as an intimate in the round.', 'https://media.timeout.com/images/105220570/1372/772/image.jpg', '35');

INSERT INTO `Events` (event_id, event_name, event_type, event_date, event_link, event_location, event_description, event_image, event_price) VALUES ('10', 'Robert Glasper', 'Music', 'Thursday October 3 2019 - Sunday November 3 2019', 'https://bluenote.net/newyork', 'Robert Glasper has reinvented himself as an R&B auteur in recent years, but here the keyboard ace demonstrates all his many sides during a month-long residency at the Blue Note. Perhaps most notably among the different configurations in which he will play: a trio with legendary rapper Yasiin Bey (f.k.a. Mos Def) special guesting..', 'https://media.timeout.com/images/101624479/1372/772/image.jpg', '45');
